### PR TITLE
resolving conflicts

### PR DESCRIPTION
**Pull request by Agni-Cast**

### CODE REVIEW

**Comment by Agni-Cast** [comment]
@saibeach @pwkoski please review my changes

**Review by saibeach — COMMENTED** [review]
@Agni-Cast  Looks great!

**Review by pwkoski — COMMENTED** [review]
looks good to me, may have to change TOKEN to token, i think it was changed to lowercase at top of file.

**Review by pwkoski — COMMENTED** [review]
I don't think we should try and merge this because bundle.js.map is in here.  I think this request should be closed and a new one without bundle.js.map can be submitted.

**Pull request merged**
