### PR TITLE
qacomponent update

### PR DESCRIPTION
**Pull request by saibeach**

### CODE REVIEW

**Review by pwkoski — COMMENTED** [review]
Why does it say package.json is deleted?  Other than that looks good.

**Comment by saibeach** [comment]
> Why does it say package.json is deleted? Other than that looks good.

i don't know why it deleted, maybe i made mistake when push to my branch

**Review by pwkoski — APPROVED** [review]
Looks good to me

**Review by Agni-Cast — APPROVED** [review]
looks good Alex

**Pull request merged**
